### ISSUE TITLE
The script to download depencecies not yet published to Maven Repositories is absent from the latest release.

### ISSUE THREAD

**Issue by BIRSAx2** [Keyfactor/signserver-ce#50]
The `lib/maven-install-files.sh`  script required to download dependencies not yet published to the Maven repositories is absent from the latest release, namely from the zip `signserver-ce-6.0.0.1.Final.zip`.
While on the zip `signserver-ce-6.0.0.1.Final-bin.zip` it's still there.

**Comment by netmackan** [comment]
Thank you for the report.
So there seems to be two issues here:
1. The missing maven-install-files.sh in the source release bundled.
2. That the dependencies are not yet published to the Central repo.

While 1. is only meant as a temporarily solution until 2. is fixed we should probably address that as well even if the dependencies are available before the next release.

**Comment by netmackan** [comment]
SignServer ticket (for future reference only, as Jira is not yet available publicly): https://jira.primekey.se/browse/DSS-2682

**Comment by mlundblad** [comment]
This should be fixed since 6.2.0.Final, so closing this now.
