### ISSUE TITLE
Unable to build from source - Failure to find com.keyfactor:x509-common-util:jar:0.7.4

### ISSUE THREAD

**Issue by blink38** [Keyfactor/signserver-ce#60]
I tried to compile signserver-ce from github source. 

I read this documentation /doc/Building_SignServer_with_Maven.html (found in my running signserver server)

I cloned latest source from github (branch main)

So I executed the command :

```shell
mvn -Dmaven.repo.local=/tmp/signserver-repo/ dependency:go-offline install -DskipTests=true
```

But I got the error : 
```
[ERROR] Failed to execute goal on project SignServer-Common: Could not resolve dependencies for project org.signserver:SignServer-Common:jar:6.2.0.Beta1-SNAPSHOT: 
Failure to find com.keyfactor:x509-common-util:jar:0.7.4 in https://ec.europa.eu/cefdigital/artifact/content/repositories/esignaturedss/ was cached in the local repository, resolution will not be reattempted until the update interval of cefdigital has elapsed or updates are forced -> [Help 1]
```
I tried using source from v6.0.0.1 tag, but I got a similar error :

```
[ERROR] Failed to execute goal on project SignServer-Common: Could not resolve dependencies for project org.signserver:SignServer-Common:jar:6.0.0.1.Final: 
Could not find artifact org.ejbca.cesecore:x509-common-util:jar:0.6.0 in cefdigital (https://ec.europa.eu/cefdigital/artifact/content/repositories/esignaturedss/) -> [Help 1]
```

**Comment by mlundblad** [comment]
Hi!

You would need to run
$ ./lib/maven-install-files.sh

To install required bundled dependencies to your local Maven repository (this is only needed when building from source, as the pre-built release will include the JAR files when building the EAR file, as part of the ANT deploy step).

**Comment by blink38** [comment]
Thanks, it resolved my problem.

I need to force using java 11 to build, otherwise I get an incompatibility with war plugin.

```
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ mvn install -DskipTests=true
```

Build was succesfull.

**Comment by mlundblad** [comment]
Yes, building with JDK later than 11 is not currently supported.

I think this issue can closed, as the initial issue was resolved?

**Comment by blink38** [comment]
Yes, this issue can be closed
