### ISSUE TITLE
Unable to access admin web console - Client certificate authentication required

### ISSUE THREAD

**Issue by blink38** [Keyfactor/signserver-ce#61]
I installed signserver v6.0.0.1.

Installation is working, I managed to sign a PDF document from client web interface.

My problem is when I tried to access admin web console, I get the error Client certificate authentication required.

I installed a certificate in a truststore and configure wildfly 26 to use it.
I include the certificate in my browser.

When accessing /signserver/adminweb/, my browser is asking me to choose the certificate, and then I get the error page :

Not Logged In
Client certificate authentication required

I'm able to access the wsdl page :  /signserver/AdminWSService/AdminWS?wsdl using the client certificate authentication.

I tried authorizing all admin to connect (```bin/signserver wsadmins -allowany true```) without success
My certificate is registered in signserver wsadmins : I can see it in the list (certserialno and issuerdn are ok)

**Comment by blink38** [comment]
Ok, I found the problem : when installing using galleon, cloud-server layers is missing.

Maybe, an update is needed in the following page :
https://doc.primekey.com/signserver/signserver-installation/application-server-setup/wildfly-24-26-and-jboss-eap-7-4

**Comment by mlundblad** [comment]
Thanks!

I created an issue for this improvement in our internal bug tracker so that we can look into it!
