### ISSUE TITLE
Can't install completely following the instruction

### ISSUE THREAD

**Issue by chiraleo2000** [Keyfactor/signserver-ce#69]
I have tried to install the signserver community edition and I got errors like JAVA library issues and compatibility and so on even when installing it with the Docker image, there is no worker tab for the signserver webpage. Can anyone help me how to do it with guidelines to install this app with the community edition to work like their video instructions and can login adminweb with possible to select TLS client certificate?

**Comment by mlundblad** [comment]
Hi!

What exactly are the library issues you get? (error messages, stack trace).

When it comes to the admin web page, did you install the client certificate in your browser's certificate store?

**Comment by mlundblad** [comment]
As there hasn't been any updates with more information in a while now, I'm closing this. Please feel free to re-open if there's additional information related to this!
